// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
// Version: 2021.1.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GIN_compute_graphs_load_graph_Pipeline_VITIS_LOOP_109_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        num_of_nodes,
        full_pe_degree_tables_address0,
        full_pe_degree_tables_ce0,
        full_pe_degree_tables_we0,
        full_pe_degree_tables_d0,
        degree_table_1_address0,
        degree_table_1_ce0,
        degree_table_1_we0,
        degree_table_1_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] num_of_nodes;
output  [8:0] full_pe_degree_tables_address0;
output   full_pe_degree_tables_ce0;
output  [15:0] full_pe_degree_tables_we0;
output  [127:0] full_pe_degree_tables_d0;
output  [8:0] degree_table_1_address0;
output   degree_table_1_ce0;
output   degree_table_1_we0;
output  [31:0] degree_table_1_d0;

reg ap_idle;
reg full_pe_degree_tables_ce0;
reg[15:0] full_pe_degree_tables_we0;
reg degree_table_1_ce0;
reg degree_table_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln109_fu_80_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] i_cast_fu_92_p1;
reg   [31:0] i_fu_36;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_5;
wire   [31:0] add_ln109_fu_86_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

GIN_compute_graphs_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln109_fu_80_p2 == 1'd0)) begin
            i_fu_36 <= add_ln109_fu_86_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_36 <= 32'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln109_fu_80_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_5 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_36;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        degree_table_1_ce0 = 1'b1;
    end else begin
        degree_table_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln109_fu_80_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        degree_table_1_we0 = 1'b1;
    end else begin
        degree_table_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        full_pe_degree_tables_ce0 = 1'b1;
    end else begin
        full_pe_degree_tables_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln109_fu_80_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        full_pe_degree_tables_we0 = 16'd65535;
    end else begin
        full_pe_degree_tables_we0 = 16'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_86_p2 = (ap_sig_allocacmp_i_5 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign degree_table_1_address0 = i_cast_fu_92_p1;

assign degree_table_1_d0 = 32'd0;

assign full_pe_degree_tables_address0 = i_cast_fu_92_p1;

assign full_pe_degree_tables_d0 = 128'd0;

assign i_cast_fu_92_p1 = ap_sig_allocacmp_i_5;

assign icmp_ln109_fu_80_p2 = ((ap_sig_allocacmp_i_5 == num_of_nodes) ? 1'b1 : 1'b0);

endmodule //GIN_compute_graphs_load_graph_Pipeline_VITIS_LOOP_109_1
