// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
// Version: 2021.1.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GIN_compute_graphs_message_passing_pe21 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer_num_dout,
        layer_num_empty_n,
        layer_num_read,
        embeddings_per_node_0_0_0_0_0345_dout,
        embeddings_per_node_0_0_0_0_0345_empty_n,
        embeddings_per_node_0_0_0_0_0345_read,
        embeddings_per_node_0_0_0_0_0346_dout,
        embeddings_per_node_0_0_0_0_0346_empty_n,
        embeddings_per_node_0_0_0_0_0346_read,
        embeddings_per_node_0_0_0_0_0347_dout,
        embeddings_per_node_0_0_0_0_0347_empty_n,
        embeddings_per_node_0_0_0_0_0347_read,
        embeddings_per_node_0_0_0_0_0348_dout,
        embeddings_per_node_0_0_0_0_0348_empty_n,
        embeddings_per_node_0_0_0_0_0348_read,
        embeddings_per_node_0_0_0_0_0349_dout,
        embeddings_per_node_0_0_0_0_0349_empty_n,
        embeddings_per_node_0_0_0_0_0349_read,
        embeddings_per_node_0_0_0_0_0350_dout,
        embeddings_per_node_0_0_0_0_0350_empty_n,
        embeddings_per_node_0_0_0_0_0350_read,
        embeddings_per_node_0_0_0_0_0351_dout,
        embeddings_per_node_0_0_0_0_0351_empty_n,
        embeddings_per_node_0_0_0_0_0351_read,
        embeddings_per_node_0_0_0_0_0352_dout,
        embeddings_per_node_0_0_0_0_0352_empty_n,
        embeddings_per_node_0_0_0_0_0352_read,
        embeddings_per_node_0_0_0_0_035_dout,
        embeddings_per_node_0_0_0_0_035_empty_n,
        embeddings_per_node_0_0_0_0_035_read,
        embeddings_per_node_0_0_0_0_03553_dout,
        embeddings_per_node_0_0_0_0_03553_empty_n,
        embeddings_per_node_0_0_0_0_03553_read,
        embeddings_per_node_0_0_0_0_03554_dout,
        embeddings_per_node_0_0_0_0_03554_empty_n,
        embeddings_per_node_0_0_0_0_03554_read,
        embeddings_per_node_0_0_0_0_03555_dout,
        embeddings_per_node_0_0_0_0_03555_empty_n,
        embeddings_per_node_0_0_0_0_03555_read,
        embeddings_per_node_0_0_0_0_03556_dout,
        embeddings_per_node_0_0_0_0_03556_empty_n,
        embeddings_per_node_0_0_0_0_03556_read,
        embeddings_per_node_0_0_0_0_03557_dout,
        embeddings_per_node_0_0_0_0_03557_empty_n,
        embeddings_per_node_0_0_0_0_03557_read,
        embeddings_per_node_0_0_0_0_03558_dout,
        embeddings_per_node_0_0_0_0_03558_empty_n,
        embeddings_per_node_0_0_0_0_03558_read,
        embeddings_per_node_0_0_0_0_03559_dout,
        embeddings_per_node_0_0_0_0_03559_empty_n,
        embeddings_per_node_0_0_0_0_03559_read,
        message627_address0,
        message627_ce0,
        message627_we0,
        message627_d0,
        message627_address1,
        message627_ce1,
        message627_q1,
        message628_address0,
        message628_ce0,
        message628_we0,
        message628_d0,
        message628_address1,
        message628_ce1,
        message628_q1,
        message629_address0,
        message629_ce0,
        message629_we0,
        message629_d0,
        message629_address1,
        message629_ce1,
        message629_q1,
        message630_address0,
        message630_ce0,
        message630_we0,
        message630_d0,
        message630_address1,
        message630_ce1,
        message630_q1,
        message631_address0,
        message631_ce0,
        message631_we0,
        message631_d0,
        message631_address1,
        message631_ce1,
        message631_q1,
        message632_address0,
        message632_ce0,
        message632_we0,
        message632_d0,
        message632_address1,
        message632_ce1,
        message632_q1,
        message633_address0,
        message633_ce0,
        message633_we0,
        message633_d0,
        message633_address1,
        message633_ce1,
        message633_q1,
        message634_address0,
        message634_ce0,
        message634_we0,
        message634_d0,
        message634_address1,
        message634_ce1,
        message634_q1,
        num_of_edges_per_pe_1_3,
        edge_embedding_weights_V_3_0_address0,
        edge_embedding_weights_V_3_0_ce0,
        edge_embedding_weights_V_3_0_q0,
        edge_embedding_weights_V_3_0_address1,
        edge_embedding_weights_V_3_0_ce1,
        edge_embedding_weights_V_3_0_q1,
        edge_embedding_weights_V_3_0_address2,
        edge_embedding_weights_V_3_0_ce2,
        edge_embedding_weights_V_3_0_q2,
        edge_embedding_weights_V_3_1_address0,
        edge_embedding_weights_V_3_1_ce0,
        edge_embedding_weights_V_3_1_q0,
        edge_embedding_weights_V_3_1_address1,
        edge_embedding_weights_V_3_1_ce1,
        edge_embedding_weights_V_3_1_q1,
        edge_embedding_weights_V_3_1_address2,
        edge_embedding_weights_V_3_1_ce2,
        edge_embedding_weights_V_3_1_q2,
        edge_embedding_weights_V_3_2_address0,
        edge_embedding_weights_V_3_2_ce0,
        edge_embedding_weights_V_3_2_q0,
        edge_embedding_weights_V_3_2_address1,
        edge_embedding_weights_V_3_2_ce1,
        edge_embedding_weights_V_3_2_q1,
        edge_embedding_weights_V_3_2_address2,
        edge_embedding_weights_V_3_2_ce2,
        edge_embedding_weights_V_3_2_q2,
        edge_embedding_weights_V_3_3_address0,
        edge_embedding_weights_V_3_3_ce0,
        edge_embedding_weights_V_3_3_q0,
        edge_embedding_weights_V_3_3_address1,
        edge_embedding_weights_V_3_3_ce1,
        edge_embedding_weights_V_3_3_q1,
        edge_embedding_weights_V_3_3_address2,
        edge_embedding_weights_V_3_3_ce2,
        edge_embedding_weights_V_3_3_q2,
        neighbor_tables_1_3_address0,
        neighbor_tables_1_3_ce0,
        neighbor_tables_1_3_q0,
        edge_attrs_1_3_address0,
        edge_attrs_1_3_ce0,
        edge_attrs_1_3_q0,
        degree_tables_1_3_address0,
        degree_tables_1_3_ce0,
        degree_tables_1_3_q0,
        edge_embedding_weights_V_3_4_address0,
        edge_embedding_weights_V_3_4_ce0,
        edge_embedding_weights_V_3_4_q0,
        edge_embedding_weights_V_3_4_address1,
        edge_embedding_weights_V_3_4_ce1,
        edge_embedding_weights_V_3_4_q1,
        edge_embedding_weights_V_3_4_address2,
        edge_embedding_weights_V_3_4_ce2,
        edge_embedding_weights_V_3_4_q2,
        edge_embedding_weights_V_3_5_address0,
        edge_embedding_weights_V_3_5_ce0,
        edge_embedding_weights_V_3_5_q0,
        edge_embedding_weights_V_3_5_address1,
        edge_embedding_weights_V_3_5_ce1,
        edge_embedding_weights_V_3_5_q1,
        edge_embedding_weights_V_3_5_address2,
        edge_embedding_weights_V_3_5_ce2,
        edge_embedding_weights_V_3_5_q2,
        edge_embedding_weights_V_3_6_address0,
        edge_embedding_weights_V_3_6_ce0,
        edge_embedding_weights_V_3_6_q0,
        edge_embedding_weights_V_3_6_address1,
        edge_embedding_weights_V_3_6_ce1,
        edge_embedding_weights_V_3_6_q1,
        edge_embedding_weights_V_3_6_address2,
        edge_embedding_weights_V_3_6_ce2,
        edge_embedding_weights_V_3_6_q2,
        edge_embedding_weights_V_3_7_address0,
        edge_embedding_weights_V_3_7_ce0,
        edge_embedding_weights_V_3_7_q0,
        edge_embedding_weights_V_3_7_address1,
        edge_embedding_weights_V_3_7_ce1,
        edge_embedding_weights_V_3_7_q1,
        edge_embedding_weights_V_3_7_address2,
        edge_embedding_weights_V_3_7_ce2,
        edge_embedding_weights_V_3_7_q2
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [2:0] layer_num_dout;
input   layer_num_empty_n;
output   layer_num_read;
input  [15:0] embeddings_per_node_0_0_0_0_0345_dout;
input   embeddings_per_node_0_0_0_0_0345_empty_n;
output   embeddings_per_node_0_0_0_0_0345_read;
input  [15:0] embeddings_per_node_0_0_0_0_0346_dout;
input   embeddings_per_node_0_0_0_0_0346_empty_n;
output   embeddings_per_node_0_0_0_0_0346_read;
input  [15:0] embeddings_per_node_0_0_0_0_0347_dout;
input   embeddings_per_node_0_0_0_0_0347_empty_n;
output   embeddings_per_node_0_0_0_0_0347_read;
input  [15:0] embeddings_per_node_0_0_0_0_0348_dout;
input   embeddings_per_node_0_0_0_0_0348_empty_n;
output   embeddings_per_node_0_0_0_0_0348_read;
input  [15:0] embeddings_per_node_0_0_0_0_0349_dout;
input   embeddings_per_node_0_0_0_0_0349_empty_n;
output   embeddings_per_node_0_0_0_0_0349_read;
input  [15:0] embeddings_per_node_0_0_0_0_0350_dout;
input   embeddings_per_node_0_0_0_0_0350_empty_n;
output   embeddings_per_node_0_0_0_0_0350_read;
input  [15:0] embeddings_per_node_0_0_0_0_0351_dout;
input   embeddings_per_node_0_0_0_0_0351_empty_n;
output   embeddings_per_node_0_0_0_0_0351_read;
input  [15:0] embeddings_per_node_0_0_0_0_0352_dout;
input   embeddings_per_node_0_0_0_0_0352_empty_n;
output   embeddings_per_node_0_0_0_0_0352_read;
input  [15:0] embeddings_per_node_0_0_0_0_035_dout;
input   embeddings_per_node_0_0_0_0_035_empty_n;
output   embeddings_per_node_0_0_0_0_035_read;
input  [15:0] embeddings_per_node_0_0_0_0_03553_dout;
input   embeddings_per_node_0_0_0_0_03553_empty_n;
output   embeddings_per_node_0_0_0_0_03553_read;
input  [15:0] embeddings_per_node_0_0_0_0_03554_dout;
input   embeddings_per_node_0_0_0_0_03554_empty_n;
output   embeddings_per_node_0_0_0_0_03554_read;
input  [15:0] embeddings_per_node_0_0_0_0_03555_dout;
input   embeddings_per_node_0_0_0_0_03555_empty_n;
output   embeddings_per_node_0_0_0_0_03555_read;
input  [15:0] embeddings_per_node_0_0_0_0_03556_dout;
input   embeddings_per_node_0_0_0_0_03556_empty_n;
output   embeddings_per_node_0_0_0_0_03556_read;
input  [15:0] embeddings_per_node_0_0_0_0_03557_dout;
input   embeddings_per_node_0_0_0_0_03557_empty_n;
output   embeddings_per_node_0_0_0_0_03557_read;
input  [15:0] embeddings_per_node_0_0_0_0_03558_dout;
input   embeddings_per_node_0_0_0_0_03558_empty_n;
output   embeddings_per_node_0_0_0_0_03558_read;
input  [15:0] embeddings_per_node_0_0_0_0_03559_dout;
input   embeddings_per_node_0_0_0_0_03559_empty_n;
output   embeddings_per_node_0_0_0_0_03559_read;
output  [10:0] message627_address0;
output   message627_ce0;
output   message627_we0;
output  [15:0] message627_d0;
output  [10:0] message627_address1;
output   message627_ce1;
input  [15:0] message627_q1;
output  [10:0] message628_address0;
output   message628_ce0;
output   message628_we0;
output  [15:0] message628_d0;
output  [10:0] message628_address1;
output   message628_ce1;
input  [15:0] message628_q1;
output  [10:0] message629_address0;
output   message629_ce0;
output   message629_we0;
output  [15:0] message629_d0;
output  [10:0] message629_address1;
output   message629_ce1;
input  [15:0] message629_q1;
output  [10:0] message630_address0;
output   message630_ce0;
output   message630_we0;
output  [15:0] message630_d0;
output  [10:0] message630_address1;
output   message630_ce1;
input  [15:0] message630_q1;
output  [10:0] message631_address0;
output   message631_ce0;
output   message631_we0;
output  [15:0] message631_d0;
output  [10:0] message631_address1;
output   message631_ce1;
input  [15:0] message631_q1;
output  [10:0] message632_address0;
output   message632_ce0;
output   message632_we0;
output  [15:0] message632_d0;
output  [10:0] message632_address1;
output   message632_ce1;
input  [15:0] message632_q1;
output  [10:0] message633_address0;
output   message633_ce0;
output   message633_we0;
output  [15:0] message633_d0;
output  [10:0] message633_address1;
output   message633_ce1;
input  [15:0] message633_q1;
output  [10:0] message634_address0;
output   message634_ce0;
output   message634_we0;
output  [15:0] message634_d0;
output  [10:0] message634_address1;
output   message634_ce1;
input  [15:0] message634_q1;
input  [31:0] num_of_edges_per_pe_1_3;
output  [9:0] edge_embedding_weights_V_3_0_address0;
output   edge_embedding_weights_V_3_0_ce0;
input  [15:0] edge_embedding_weights_V_3_0_q0;
output  [9:0] edge_embedding_weights_V_3_0_address1;
output   edge_embedding_weights_V_3_0_ce1;
input  [15:0] edge_embedding_weights_V_3_0_q1;
output  [9:0] edge_embedding_weights_V_3_0_address2;
output   edge_embedding_weights_V_3_0_ce2;
input  [15:0] edge_embedding_weights_V_3_0_q2;
output  [9:0] edge_embedding_weights_V_3_1_address0;
output   edge_embedding_weights_V_3_1_ce0;
input  [15:0] edge_embedding_weights_V_3_1_q0;
output  [9:0] edge_embedding_weights_V_3_1_address1;
output   edge_embedding_weights_V_3_1_ce1;
input  [15:0] edge_embedding_weights_V_3_1_q1;
output  [9:0] edge_embedding_weights_V_3_1_address2;
output   edge_embedding_weights_V_3_1_ce2;
input  [15:0] edge_embedding_weights_V_3_1_q2;
output  [9:0] edge_embedding_weights_V_3_2_address0;
output   edge_embedding_weights_V_3_2_ce0;
input  [15:0] edge_embedding_weights_V_3_2_q0;
output  [9:0] edge_embedding_weights_V_3_2_address1;
output   edge_embedding_weights_V_3_2_ce1;
input  [15:0] edge_embedding_weights_V_3_2_q1;
output  [9:0] edge_embedding_weights_V_3_2_address2;
output   edge_embedding_weights_V_3_2_ce2;
input  [15:0] edge_embedding_weights_V_3_2_q2;
output  [9:0] edge_embedding_weights_V_3_3_address0;
output   edge_embedding_weights_V_3_3_ce0;
input  [15:0] edge_embedding_weights_V_3_3_q0;
output  [9:0] edge_embedding_weights_V_3_3_address1;
output   edge_embedding_weights_V_3_3_ce1;
input  [15:0] edge_embedding_weights_V_3_3_q1;
output  [9:0] edge_embedding_weights_V_3_3_address2;
output   edge_embedding_weights_V_3_3_ce2;
input  [15:0] edge_embedding_weights_V_3_3_q2;
output  [8:0] neighbor_tables_1_3_address0;
output   neighbor_tables_1_3_ce0;
input  [6:0] neighbor_tables_1_3_q0;
output  [8:0] edge_attrs_1_3_address0;
output   edge_attrs_1_3_ce0;
input  [70:0] edge_attrs_1_3_q0;
output  [8:0] degree_tables_1_3_address0;
output   degree_tables_1_3_ce0;
input  [63:0] degree_tables_1_3_q0;
output  [9:0] edge_embedding_weights_V_3_4_address0;
output   edge_embedding_weights_V_3_4_ce0;
input  [15:0] edge_embedding_weights_V_3_4_q0;
output  [9:0] edge_embedding_weights_V_3_4_address1;
output   edge_embedding_weights_V_3_4_ce1;
input  [15:0] edge_embedding_weights_V_3_4_q1;
output  [9:0] edge_embedding_weights_V_3_4_address2;
output   edge_embedding_weights_V_3_4_ce2;
input  [15:0] edge_embedding_weights_V_3_4_q2;
output  [9:0] edge_embedding_weights_V_3_5_address0;
output   edge_embedding_weights_V_3_5_ce0;
input  [15:0] edge_embedding_weights_V_3_5_q0;
output  [9:0] edge_embedding_weights_V_3_5_address1;
output   edge_embedding_weights_V_3_5_ce1;
input  [15:0] edge_embedding_weights_V_3_5_q1;
output  [9:0] edge_embedding_weights_V_3_5_address2;
output   edge_embedding_weights_V_3_5_ce2;
input  [15:0] edge_embedding_weights_V_3_5_q2;
output  [9:0] edge_embedding_weights_V_3_6_address0;
output   edge_embedding_weights_V_3_6_ce0;
input  [15:0] edge_embedding_weights_V_3_6_q0;
output  [9:0] edge_embedding_weights_V_3_6_address1;
output   edge_embedding_weights_V_3_6_ce1;
input  [15:0] edge_embedding_weights_V_3_6_q1;
output  [9:0] edge_embedding_weights_V_3_6_address2;
output   edge_embedding_weights_V_3_6_ce2;
input  [15:0] edge_embedding_weights_V_3_6_q2;
output  [9:0] edge_embedding_weights_V_3_7_address0;
output   edge_embedding_weights_V_3_7_ce0;
input  [15:0] edge_embedding_weights_V_3_7_q0;
output  [9:0] edge_embedding_weights_V_3_7_address1;
output   edge_embedding_weights_V_3_7_ce1;
input  [15:0] edge_embedding_weights_V_3_7_q1;
output  [9:0] edge_embedding_weights_V_3_7_address2;
output   edge_embedding_weights_V_3_7_ce2;
input  [15:0] edge_embedding_weights_V_3_7_q2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer_num_read;
reg embeddings_per_node_0_0_0_0_0345_read;
reg embeddings_per_node_0_0_0_0_0346_read;
reg embeddings_per_node_0_0_0_0_0347_read;
reg embeddings_per_node_0_0_0_0_0348_read;
reg embeddings_per_node_0_0_0_0_0349_read;
reg embeddings_per_node_0_0_0_0_0350_read;
reg embeddings_per_node_0_0_0_0_0351_read;
reg embeddings_per_node_0_0_0_0_0352_read;
reg embeddings_per_node_0_0_0_0_035_read;
reg embeddings_per_node_0_0_0_0_03553_read;
reg embeddings_per_node_0_0_0_0_03554_read;
reg embeddings_per_node_0_0_0_0_03555_read;
reg embeddings_per_node_0_0_0_0_03556_read;
reg embeddings_per_node_0_0_0_0_03557_read;
reg embeddings_per_node_0_0_0_0_03558_read;
reg embeddings_per_node_0_0_0_0_03559_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer_num_blk_n;
wire    ap_CS_fsm_state2;
wire   [6:0] mul_ln712_fu_254_p2;
reg   [6:0] mul_ln712_reg_265;
wire   [35:0] grp_fu_244_p2;
reg   [35:0] bound_reg_270;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0345_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0346_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0347_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0348_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0349_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0350_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0351_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0352_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_035_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03553_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03554_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03555_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03556_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03557_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03558_read;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03559_read;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce1;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_we0;
wire   [15:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_d0;
wire   [10:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce2;
wire   [8:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_ce0;
wire   [8:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_ce0;
wire   [8:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce2;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address0;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce0;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address1;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce1;
wire   [9:0] grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address2;
wire    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce2;
reg    grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
wire   [31:0] grp_fu_244_p0;
wire   [4:0] grp_fu_244_p1;
wire   [2:0] mul_ln712_fu_254_p0;
wire   [4:0] mul_ln712_fu_254_p1;
reg    grp_fu_244_ce;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire   [35:0] grp_fu_244_p00;
wire   [6:0] mul_ln712_fu_254_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg = 1'b0;
end

GIN_compute_graphs_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2 grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start),
    .ap_done(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done),
    .ap_idle(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle),
    .ap_ready(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready),
    .embeddings_per_node_0_0_0_0_0345_dout(embeddings_per_node_0_0_0_0_0345_dout),
    .embeddings_per_node_0_0_0_0_0345_empty_n(embeddings_per_node_0_0_0_0_0345_empty_n),
    .embeddings_per_node_0_0_0_0_0345_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0345_read),
    .embeddings_per_node_0_0_0_0_0346_dout(embeddings_per_node_0_0_0_0_0346_dout),
    .embeddings_per_node_0_0_0_0_0346_empty_n(embeddings_per_node_0_0_0_0_0346_empty_n),
    .embeddings_per_node_0_0_0_0_0346_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0346_read),
    .embeddings_per_node_0_0_0_0_0347_dout(embeddings_per_node_0_0_0_0_0347_dout),
    .embeddings_per_node_0_0_0_0_0347_empty_n(embeddings_per_node_0_0_0_0_0347_empty_n),
    .embeddings_per_node_0_0_0_0_0347_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0347_read),
    .embeddings_per_node_0_0_0_0_0348_dout(embeddings_per_node_0_0_0_0_0348_dout),
    .embeddings_per_node_0_0_0_0_0348_empty_n(embeddings_per_node_0_0_0_0_0348_empty_n),
    .embeddings_per_node_0_0_0_0_0348_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0348_read),
    .embeddings_per_node_0_0_0_0_0349_dout(embeddings_per_node_0_0_0_0_0349_dout),
    .embeddings_per_node_0_0_0_0_0349_empty_n(embeddings_per_node_0_0_0_0_0349_empty_n),
    .embeddings_per_node_0_0_0_0_0349_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0349_read),
    .embeddings_per_node_0_0_0_0_0350_dout(embeddings_per_node_0_0_0_0_0350_dout),
    .embeddings_per_node_0_0_0_0_0350_empty_n(embeddings_per_node_0_0_0_0_0350_empty_n),
    .embeddings_per_node_0_0_0_0_0350_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0350_read),
    .embeddings_per_node_0_0_0_0_0351_dout(embeddings_per_node_0_0_0_0_0351_dout),
    .embeddings_per_node_0_0_0_0_0351_empty_n(embeddings_per_node_0_0_0_0_0351_empty_n),
    .embeddings_per_node_0_0_0_0_0351_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0351_read),
    .embeddings_per_node_0_0_0_0_0352_dout(embeddings_per_node_0_0_0_0_0352_dout),
    .embeddings_per_node_0_0_0_0_0352_empty_n(embeddings_per_node_0_0_0_0_0352_empty_n),
    .embeddings_per_node_0_0_0_0_0352_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0352_read),
    .embeddings_per_node_0_0_0_0_035_dout(embeddings_per_node_0_0_0_0_035_dout),
    .embeddings_per_node_0_0_0_0_035_empty_n(embeddings_per_node_0_0_0_0_035_empty_n),
    .embeddings_per_node_0_0_0_0_035_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_035_read),
    .embeddings_per_node_0_0_0_0_03553_dout(embeddings_per_node_0_0_0_0_03553_dout),
    .embeddings_per_node_0_0_0_0_03553_empty_n(embeddings_per_node_0_0_0_0_03553_empty_n),
    .embeddings_per_node_0_0_0_0_03553_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03553_read),
    .embeddings_per_node_0_0_0_0_03554_dout(embeddings_per_node_0_0_0_0_03554_dout),
    .embeddings_per_node_0_0_0_0_03554_empty_n(embeddings_per_node_0_0_0_0_03554_empty_n),
    .embeddings_per_node_0_0_0_0_03554_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03554_read),
    .embeddings_per_node_0_0_0_0_03555_dout(embeddings_per_node_0_0_0_0_03555_dout),
    .embeddings_per_node_0_0_0_0_03555_empty_n(embeddings_per_node_0_0_0_0_03555_empty_n),
    .embeddings_per_node_0_0_0_0_03555_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03555_read),
    .embeddings_per_node_0_0_0_0_03556_dout(embeddings_per_node_0_0_0_0_03556_dout),
    .embeddings_per_node_0_0_0_0_03556_empty_n(embeddings_per_node_0_0_0_0_03556_empty_n),
    .embeddings_per_node_0_0_0_0_03556_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03556_read),
    .embeddings_per_node_0_0_0_0_03557_dout(embeddings_per_node_0_0_0_0_03557_dout),
    .embeddings_per_node_0_0_0_0_03557_empty_n(embeddings_per_node_0_0_0_0_03557_empty_n),
    .embeddings_per_node_0_0_0_0_03557_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03557_read),
    .embeddings_per_node_0_0_0_0_03558_dout(embeddings_per_node_0_0_0_0_03558_dout),
    .embeddings_per_node_0_0_0_0_03558_empty_n(embeddings_per_node_0_0_0_0_03558_empty_n),
    .embeddings_per_node_0_0_0_0_03558_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03558_read),
    .embeddings_per_node_0_0_0_0_03559_dout(embeddings_per_node_0_0_0_0_03559_dout),
    .embeddings_per_node_0_0_0_0_03559_empty_n(embeddings_per_node_0_0_0_0_03559_empty_n),
    .embeddings_per_node_0_0_0_0_03559_read(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03559_read),
    .bound(bound_reg_270),
    .mul_ln712(mul_ln712_reg_265),
    .message627_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address0),
    .message627_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce0),
    .message627_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_we0),
    .message627_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_d0),
    .message627_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address1),
    .message627_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce1),
    .message627_q1(message627_q1),
    .message628_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address0),
    .message628_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce0),
    .message628_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_we0),
    .message628_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_d0),
    .message628_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address1),
    .message628_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce1),
    .message628_q1(message628_q1),
    .message629_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address0),
    .message629_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce0),
    .message629_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_we0),
    .message629_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_d0),
    .message629_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address1),
    .message629_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce1),
    .message629_q1(message629_q1),
    .message630_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address0),
    .message630_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce0),
    .message630_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_we0),
    .message630_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_d0),
    .message630_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address1),
    .message630_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce1),
    .message630_q1(message630_q1),
    .message631_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address0),
    .message631_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce0),
    .message631_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_we0),
    .message631_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_d0),
    .message631_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address1),
    .message631_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce1),
    .message631_q1(message631_q1),
    .message632_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address0),
    .message632_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce0),
    .message632_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_we0),
    .message632_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_d0),
    .message632_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address1),
    .message632_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce1),
    .message632_q1(message632_q1),
    .message633_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address0),
    .message633_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce0),
    .message633_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_we0),
    .message633_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_d0),
    .message633_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address1),
    .message633_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce1),
    .message633_q1(message633_q1),
    .message634_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address0),
    .message634_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce0),
    .message634_we0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_we0),
    .message634_d0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_d0),
    .message634_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address1),
    .message634_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce1),
    .message634_q1(message634_q1),
    .edge_embedding_weights_V_3_0_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address0),
    .edge_embedding_weights_V_3_0_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce0),
    .edge_embedding_weights_V_3_0_q0(edge_embedding_weights_V_3_0_q0),
    .edge_embedding_weights_V_3_0_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address1),
    .edge_embedding_weights_V_3_0_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce1),
    .edge_embedding_weights_V_3_0_q1(edge_embedding_weights_V_3_0_q1),
    .edge_embedding_weights_V_3_0_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address2),
    .edge_embedding_weights_V_3_0_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce2),
    .edge_embedding_weights_V_3_0_q2(edge_embedding_weights_V_3_0_q2),
    .edge_embedding_weights_V_3_1_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address0),
    .edge_embedding_weights_V_3_1_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce0),
    .edge_embedding_weights_V_3_1_q0(edge_embedding_weights_V_3_1_q0),
    .edge_embedding_weights_V_3_1_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address1),
    .edge_embedding_weights_V_3_1_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce1),
    .edge_embedding_weights_V_3_1_q1(edge_embedding_weights_V_3_1_q1),
    .edge_embedding_weights_V_3_1_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address2),
    .edge_embedding_weights_V_3_1_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce2),
    .edge_embedding_weights_V_3_1_q2(edge_embedding_weights_V_3_1_q2),
    .edge_embedding_weights_V_3_2_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address0),
    .edge_embedding_weights_V_3_2_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce0),
    .edge_embedding_weights_V_3_2_q0(edge_embedding_weights_V_3_2_q0),
    .edge_embedding_weights_V_3_2_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address1),
    .edge_embedding_weights_V_3_2_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce1),
    .edge_embedding_weights_V_3_2_q1(edge_embedding_weights_V_3_2_q1),
    .edge_embedding_weights_V_3_2_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address2),
    .edge_embedding_weights_V_3_2_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce2),
    .edge_embedding_weights_V_3_2_q2(edge_embedding_weights_V_3_2_q2),
    .edge_embedding_weights_V_3_3_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address0),
    .edge_embedding_weights_V_3_3_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce0),
    .edge_embedding_weights_V_3_3_q0(edge_embedding_weights_V_3_3_q0),
    .edge_embedding_weights_V_3_3_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address1),
    .edge_embedding_weights_V_3_3_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce1),
    .edge_embedding_weights_V_3_3_q1(edge_embedding_weights_V_3_3_q1),
    .edge_embedding_weights_V_3_3_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address2),
    .edge_embedding_weights_V_3_3_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce2),
    .edge_embedding_weights_V_3_3_q2(edge_embedding_weights_V_3_3_q2),
    .neighbor_tables_1_3_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_address0),
    .neighbor_tables_1_3_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_ce0),
    .neighbor_tables_1_3_q0(neighbor_tables_1_3_q0),
    .edge_attrs_1_3_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_address0),
    .edge_attrs_1_3_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_ce0),
    .edge_attrs_1_3_q0(edge_attrs_1_3_q0),
    .degree_tables_1_3_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_address0),
    .degree_tables_1_3_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_ce0),
    .degree_tables_1_3_q0(degree_tables_1_3_q0),
    .edge_embedding_weights_V_3_4_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address0),
    .edge_embedding_weights_V_3_4_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce0),
    .edge_embedding_weights_V_3_4_q0(edge_embedding_weights_V_3_4_q0),
    .edge_embedding_weights_V_3_4_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address1),
    .edge_embedding_weights_V_3_4_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce1),
    .edge_embedding_weights_V_3_4_q1(edge_embedding_weights_V_3_4_q1),
    .edge_embedding_weights_V_3_4_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address2),
    .edge_embedding_weights_V_3_4_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce2),
    .edge_embedding_weights_V_3_4_q2(edge_embedding_weights_V_3_4_q2),
    .edge_embedding_weights_V_3_5_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address0),
    .edge_embedding_weights_V_3_5_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce0),
    .edge_embedding_weights_V_3_5_q0(edge_embedding_weights_V_3_5_q0),
    .edge_embedding_weights_V_3_5_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address1),
    .edge_embedding_weights_V_3_5_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce1),
    .edge_embedding_weights_V_3_5_q1(edge_embedding_weights_V_3_5_q1),
    .edge_embedding_weights_V_3_5_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address2),
    .edge_embedding_weights_V_3_5_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce2),
    .edge_embedding_weights_V_3_5_q2(edge_embedding_weights_V_3_5_q2),
    .edge_embedding_weights_V_3_6_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address0),
    .edge_embedding_weights_V_3_6_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce0),
    .edge_embedding_weights_V_3_6_q0(edge_embedding_weights_V_3_6_q0),
    .edge_embedding_weights_V_3_6_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address1),
    .edge_embedding_weights_V_3_6_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce1),
    .edge_embedding_weights_V_3_6_q1(edge_embedding_weights_V_3_6_q1),
    .edge_embedding_weights_V_3_6_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address2),
    .edge_embedding_weights_V_3_6_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce2),
    .edge_embedding_weights_V_3_6_q2(edge_embedding_weights_V_3_6_q2),
    .edge_embedding_weights_V_3_7_address0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address0),
    .edge_embedding_weights_V_3_7_ce0(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce0),
    .edge_embedding_weights_V_3_7_q0(edge_embedding_weights_V_3_7_q0),
    .edge_embedding_weights_V_3_7_address1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address1),
    .edge_embedding_weights_V_3_7_ce1(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce1),
    .edge_embedding_weights_V_3_7_q1(edge_embedding_weights_V_3_7_q1),
    .edge_embedding_weights_V_3_7_address2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address2),
    .edge_embedding_weights_V_3_7_ce2(grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce2),
    .edge_embedding_weights_V_3_7_q2(edge_embedding_weights_V_3_7_q2)
);

GIN_compute_graphs_mul_32ns_5ns_36_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 36 ))
mul_32ns_5ns_36_2_1_U6514(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_244_p0),
    .din1(grp_fu_244_p1),
    .ce(grp_fu_244_ce),
    .dout(grp_fu_244_p2)
);

GIN_compute_graphs_mul_3ns_5ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
mul_3ns_5ns_7_1_1_U6515(
    .din0(mul_ln712_fu_254_p0),
    .din1(mul_ln712_fu_254_p1),
    .dout(mul_ln712_fu_254_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready == 1'b1)) begin
            grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_270 <= grp_fu_244_p2;
        mul_ln712_reg_265 <= mul_ln712_fu_254_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer_num_empty_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0345_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0345_read;
    end else begin
        embeddings_per_node_0_0_0_0_0345_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0346_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0346_read;
    end else begin
        embeddings_per_node_0_0_0_0_0346_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0347_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0347_read;
    end else begin
        embeddings_per_node_0_0_0_0_0347_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0348_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0348_read;
    end else begin
        embeddings_per_node_0_0_0_0_0348_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0349_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0349_read;
    end else begin
        embeddings_per_node_0_0_0_0_0349_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0350_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0350_read;
    end else begin
        embeddings_per_node_0_0_0_0_0350_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0351_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0351_read;
    end else begin
        embeddings_per_node_0_0_0_0_0351_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_0352_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0352_read;
    end else begin
        embeddings_per_node_0_0_0_0_0352_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03553_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03553_read;
    end else begin
        embeddings_per_node_0_0_0_0_03553_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03554_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03554_read;
    end else begin
        embeddings_per_node_0_0_0_0_03554_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03555_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03555_read;
    end else begin
        embeddings_per_node_0_0_0_0_03555_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03556_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03556_read;
    end else begin
        embeddings_per_node_0_0_0_0_03556_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03557_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03557_read;
    end else begin
        embeddings_per_node_0_0_0_0_03557_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03558_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03558_read;
    end else begin
        embeddings_per_node_0_0_0_0_03558_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_03559_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03559_read;
    end else begin
        embeddings_per_node_0_0_0_0_03559_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        embeddings_per_node_0_0_0_0_035_read = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_035_read;
    end else begin
        embeddings_per_node_0_0_0_0_035_read = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((layer_num_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_fu_244_ce = 1'b1;
    end else begin
        grp_fu_244_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer_num_blk_n = layer_num_empty_n;
    end else begin
        layer_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer_num_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer_num_read = 1'b1;
    end else begin
        layer_num_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer_num_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign degree_tables_1_3_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_address0;

assign degree_tables_1_3_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_3_ce0;

assign edge_attrs_1_3_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_address0;

assign edge_attrs_1_3_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_3_ce0;

assign edge_embedding_weights_V_3_0_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address0;

assign edge_embedding_weights_V_3_0_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address1;

assign edge_embedding_weights_V_3_0_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_address2;

assign edge_embedding_weights_V_3_0_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce0;

assign edge_embedding_weights_V_3_0_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce1;

assign edge_embedding_weights_V_3_0_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_0_ce2;

assign edge_embedding_weights_V_3_1_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address0;

assign edge_embedding_weights_V_3_1_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address1;

assign edge_embedding_weights_V_3_1_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_address2;

assign edge_embedding_weights_V_3_1_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce0;

assign edge_embedding_weights_V_3_1_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce1;

assign edge_embedding_weights_V_3_1_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_1_ce2;

assign edge_embedding_weights_V_3_2_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address0;

assign edge_embedding_weights_V_3_2_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address1;

assign edge_embedding_weights_V_3_2_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_address2;

assign edge_embedding_weights_V_3_2_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce0;

assign edge_embedding_weights_V_3_2_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce1;

assign edge_embedding_weights_V_3_2_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_2_ce2;

assign edge_embedding_weights_V_3_3_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address0;

assign edge_embedding_weights_V_3_3_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address1;

assign edge_embedding_weights_V_3_3_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_address2;

assign edge_embedding_weights_V_3_3_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce0;

assign edge_embedding_weights_V_3_3_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce1;

assign edge_embedding_weights_V_3_3_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_3_ce2;

assign edge_embedding_weights_V_3_4_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address0;

assign edge_embedding_weights_V_3_4_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address1;

assign edge_embedding_weights_V_3_4_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_address2;

assign edge_embedding_weights_V_3_4_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce0;

assign edge_embedding_weights_V_3_4_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce1;

assign edge_embedding_weights_V_3_4_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_4_ce2;

assign edge_embedding_weights_V_3_5_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address0;

assign edge_embedding_weights_V_3_5_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address1;

assign edge_embedding_weights_V_3_5_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_address2;

assign edge_embedding_weights_V_3_5_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce0;

assign edge_embedding_weights_V_3_5_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce1;

assign edge_embedding_weights_V_3_5_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_5_ce2;

assign edge_embedding_weights_V_3_6_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address0;

assign edge_embedding_weights_V_3_6_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address1;

assign edge_embedding_weights_V_3_6_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_address2;

assign edge_embedding_weights_V_3_6_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce0;

assign edge_embedding_weights_V_3_6_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce1;

assign edge_embedding_weights_V_3_6_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_6_ce2;

assign edge_embedding_weights_V_3_7_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address0;

assign edge_embedding_weights_V_3_7_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address1;

assign edge_embedding_weights_V_3_7_address2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_address2;

assign edge_embedding_weights_V_3_7_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce0;

assign edge_embedding_weights_V_3_7_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce1;

assign edge_embedding_weights_V_3_7_ce2 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_3_7_ce2;

assign grp_fu_244_p0 = grp_fu_244_p00;

assign grp_fu_244_p00 = num_of_edges_per_pe_1_3;

assign grp_fu_244_p1 = 36'd13;

assign grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg;

assign message627_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address0;

assign message627_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_address1;

assign message627_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce0;

assign message627_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_ce1;

assign message627_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_d0;

assign message627_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message627_we0;

assign message628_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address0;

assign message628_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_address1;

assign message628_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce0;

assign message628_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_ce1;

assign message628_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_d0;

assign message628_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message628_we0;

assign message629_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address0;

assign message629_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_address1;

assign message629_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce0;

assign message629_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_ce1;

assign message629_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_d0;

assign message629_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message629_we0;

assign message630_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address0;

assign message630_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_address1;

assign message630_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce0;

assign message630_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_ce1;

assign message630_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_d0;

assign message630_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message630_we0;

assign message631_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address0;

assign message631_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_address1;

assign message631_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce0;

assign message631_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_ce1;

assign message631_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_d0;

assign message631_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message631_we0;

assign message632_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address0;

assign message632_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_address1;

assign message632_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce0;

assign message632_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_ce1;

assign message632_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_d0;

assign message632_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message632_we0;

assign message633_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address0;

assign message633_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_address1;

assign message633_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce0;

assign message633_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_ce1;

assign message633_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_d0;

assign message633_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message633_we0;

assign message634_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address0;

assign message634_address1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_address1;

assign message634_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce0;

assign message634_ce1 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_ce1;

assign message634_d0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_d0;

assign message634_we0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message634_we0;

assign mul_ln712_fu_254_p0 = mul_ln712_fu_254_p00;

assign mul_ln712_fu_254_p00 = layer_num_dout;

assign mul_ln712_fu_254_p1 = 7'd13;

assign neighbor_tables_1_3_address0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_address0;

assign neighbor_tables_1_3_ce0 = grp_message_passing_pe21_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_3_ce0;

endmodule //GIN_compute_graphs_message_passing_pe21
