-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
-- Version: 2021.1.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GIN_compute_graphs_message_passing_pe18 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer_num_dout : IN STD_LOGIC_VECTOR (2 downto 0);
    layer_num_empty_n : IN STD_LOGIC;
    layer_num_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_02_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_02_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_02_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_03_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_03_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_03_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_04_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_04_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_04_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_05_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_05_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_05_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_06_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_06_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_06_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_07_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_07_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_07_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_018_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_018_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_018_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_019_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_019_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_019_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0110_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0110_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0110_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0111_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0111_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0111_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0112_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0112_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0112_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0113_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0113_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0113_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0114_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0114_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0114_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_0115_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_0115_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_0115_read : OUT STD_LOGIC;
    message_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message_ce0 : OUT STD_LOGIC;
    message_we0 : OUT STD_LOGIC;
    message_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message_ce1 : OUT STD_LOGIC;
    message_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message6_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message6_ce0 : OUT STD_LOGIC;
    message6_we0 : OUT STD_LOGIC;
    message6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message6_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message6_ce1 : OUT STD_LOGIC;
    message6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message7_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message7_ce0 : OUT STD_LOGIC;
    message7_we0 : OUT STD_LOGIC;
    message7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message7_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message7_ce1 : OUT STD_LOGIC;
    message7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message8_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message8_ce0 : OUT STD_LOGIC;
    message8_we0 : OUT STD_LOGIC;
    message8_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message8_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message8_ce1 : OUT STD_LOGIC;
    message8_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message9_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message9_ce0 : OUT STD_LOGIC;
    message9_we0 : OUT STD_LOGIC;
    message9_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message9_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message9_ce1 : OUT STD_LOGIC;
    message9_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message10_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message10_ce0 : OUT STD_LOGIC;
    message10_we0 : OUT STD_LOGIC;
    message10_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message10_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message10_ce1 : OUT STD_LOGIC;
    message10_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message11_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message11_ce0 : OUT STD_LOGIC;
    message11_we0 : OUT STD_LOGIC;
    message11_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message11_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message11_ce1 : OUT STD_LOGIC;
    message11_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message12_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message12_ce0 : OUT STD_LOGIC;
    message12_we0 : OUT STD_LOGIC;
    message12_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message12_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message12_ce1 : OUT STD_LOGIC;
    message12_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    num_of_edges_per_pe_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_embedding_weights_V_0_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_0_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_0_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_0_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_0_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_0_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_1_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_1_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_1_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_1_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_1_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_2_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_2_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_2_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_2_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_2_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_3_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_3_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_3_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_3_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_3_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    neighbor_tables_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    neighbor_tables_1_0_ce0 : OUT STD_LOGIC;
    neighbor_tables_1_0_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    edge_attrs_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    edge_attrs_1_0_ce0 : OUT STD_LOGIC;
    edge_attrs_1_0_q0 : IN STD_LOGIC_VECTOR (70 downto 0);
    degree_tables_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    degree_tables_1_0_ce0 : OUT STD_LOGIC;
    degree_tables_1_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    edge_embedding_weights_V_0_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_4_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_4_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_4_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_4_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_4_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_5_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_5_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_5_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_5_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_5_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_6_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_6_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_6_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_6_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_6_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_7_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_7_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_0_7_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_0_7_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_0_7_q2 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of GIN_compute_graphs_message_passing_pe18 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv36_D : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000001101";
    constant ap_const_lv7_D : STD_LOGIC_VECTOR (6 downto 0) := "0001101";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer_num_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln712_fu_254_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln712_reg_265 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_244_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal bound_reg_270 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_02_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_04_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_05_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_06_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_07_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_018_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_019_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0110_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0111_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0112_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0113_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0114_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0115_read : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_we0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce0 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce1 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce2 : STD_LOGIC;
    signal grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_244_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_244_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln712_fu_254_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln712_fu_254_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_244_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal grp_fu_244_p00 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln712_fu_254_p00 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component GIN_compute_graphs_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_02_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_02_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_02_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_03_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_03_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_03_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_04_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_04_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_04_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_05_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_05_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_05_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_06_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_06_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_06_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_07_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_07_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_07_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_018_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_018_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_018_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_019_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_019_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_019_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0110_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0110_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0110_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0111_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0111_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0111_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0112_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0112_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0112_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0113_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0113_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0113_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0114_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0114_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0114_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_0115_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_0115_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_0115_read : OUT STD_LOGIC;
        bound : IN STD_LOGIC_VECTOR (35 downto 0);
        mul_ln712 : IN STD_LOGIC_VECTOR (6 downto 0);
        message_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message_ce0 : OUT STD_LOGIC;
        message_we0 : OUT STD_LOGIC;
        message_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message_ce1 : OUT STD_LOGIC;
        message_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message6_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message6_ce0 : OUT STD_LOGIC;
        message6_we0 : OUT STD_LOGIC;
        message6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message6_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message6_ce1 : OUT STD_LOGIC;
        message6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message7_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message7_ce0 : OUT STD_LOGIC;
        message7_we0 : OUT STD_LOGIC;
        message7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message7_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message7_ce1 : OUT STD_LOGIC;
        message7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message8_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message8_ce0 : OUT STD_LOGIC;
        message8_we0 : OUT STD_LOGIC;
        message8_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message8_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message8_ce1 : OUT STD_LOGIC;
        message8_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message9_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message9_ce0 : OUT STD_LOGIC;
        message9_we0 : OUT STD_LOGIC;
        message9_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message9_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message9_ce1 : OUT STD_LOGIC;
        message9_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message10_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message10_ce0 : OUT STD_LOGIC;
        message10_we0 : OUT STD_LOGIC;
        message10_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message10_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message10_ce1 : OUT STD_LOGIC;
        message10_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message11_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message11_ce0 : OUT STD_LOGIC;
        message11_we0 : OUT STD_LOGIC;
        message11_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message11_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message11_ce1 : OUT STD_LOGIC;
        message11_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message12_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message12_ce0 : OUT STD_LOGIC;
        message12_we0 : OUT STD_LOGIC;
        message12_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message12_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message12_ce1 : OUT STD_LOGIC;
        message12_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_0_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_0_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_0_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_0_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_0_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_1_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_1_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_1_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_1_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_1_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_2_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_2_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_2_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_2_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_2_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_3_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_3_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_3_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_3_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_3_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        neighbor_tables_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        neighbor_tables_1_0_ce0 : OUT STD_LOGIC;
        neighbor_tables_1_0_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
        edge_attrs_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        edge_attrs_1_0_ce0 : OUT STD_LOGIC;
        edge_attrs_1_0_q0 : IN STD_LOGIC_VECTOR (70 downto 0);
        degree_tables_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        degree_tables_1_0_ce0 : OUT STD_LOGIC;
        degree_tables_1_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        edge_embedding_weights_V_0_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_4_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_4_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_4_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_4_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_4_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_5_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_5_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_5_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_5_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_5_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_6_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_6_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_6_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_6_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_6_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_7_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_7_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_0_7_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_0_7_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_0_7_q2 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component GIN_compute_graphs_mul_32ns_5ns_36_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component GIN_compute_graphs_mul_3ns_5ns_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160 : component GIN_compute_graphs_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start,
        ap_done => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done,
        ap_idle => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle,
        ap_ready => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready,
        embeddings_per_node_0_0_0_0_0_dout => embeddings_per_node_0_0_0_0_0_dout,
        embeddings_per_node_0_0_0_0_0_empty_n => embeddings_per_node_0_0_0_0_0_empty_n,
        embeddings_per_node_0_0_0_0_0_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0_read,
        embeddings_per_node_0_0_0_0_01_dout => embeddings_per_node_0_0_0_0_01_dout,
        embeddings_per_node_0_0_0_0_01_empty_n => embeddings_per_node_0_0_0_0_01_empty_n,
        embeddings_per_node_0_0_0_0_01_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01_read,
        embeddings_per_node_0_0_0_0_02_dout => embeddings_per_node_0_0_0_0_02_dout,
        embeddings_per_node_0_0_0_0_02_empty_n => embeddings_per_node_0_0_0_0_02_empty_n,
        embeddings_per_node_0_0_0_0_02_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_02_read,
        embeddings_per_node_0_0_0_0_03_dout => embeddings_per_node_0_0_0_0_03_dout,
        embeddings_per_node_0_0_0_0_03_empty_n => embeddings_per_node_0_0_0_0_03_empty_n,
        embeddings_per_node_0_0_0_0_03_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03_read,
        embeddings_per_node_0_0_0_0_04_dout => embeddings_per_node_0_0_0_0_04_dout,
        embeddings_per_node_0_0_0_0_04_empty_n => embeddings_per_node_0_0_0_0_04_empty_n,
        embeddings_per_node_0_0_0_0_04_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_04_read,
        embeddings_per_node_0_0_0_0_05_dout => embeddings_per_node_0_0_0_0_05_dout,
        embeddings_per_node_0_0_0_0_05_empty_n => embeddings_per_node_0_0_0_0_05_empty_n,
        embeddings_per_node_0_0_0_0_05_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_05_read,
        embeddings_per_node_0_0_0_0_06_dout => embeddings_per_node_0_0_0_0_06_dout,
        embeddings_per_node_0_0_0_0_06_empty_n => embeddings_per_node_0_0_0_0_06_empty_n,
        embeddings_per_node_0_0_0_0_06_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_06_read,
        embeddings_per_node_0_0_0_0_07_dout => embeddings_per_node_0_0_0_0_07_dout,
        embeddings_per_node_0_0_0_0_07_empty_n => embeddings_per_node_0_0_0_0_07_empty_n,
        embeddings_per_node_0_0_0_0_07_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_07_read,
        embeddings_per_node_0_0_0_0_018_dout => embeddings_per_node_0_0_0_0_018_dout,
        embeddings_per_node_0_0_0_0_018_empty_n => embeddings_per_node_0_0_0_0_018_empty_n,
        embeddings_per_node_0_0_0_0_018_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_018_read,
        embeddings_per_node_0_0_0_0_019_dout => embeddings_per_node_0_0_0_0_019_dout,
        embeddings_per_node_0_0_0_0_019_empty_n => embeddings_per_node_0_0_0_0_019_empty_n,
        embeddings_per_node_0_0_0_0_019_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_019_read,
        embeddings_per_node_0_0_0_0_0110_dout => embeddings_per_node_0_0_0_0_0110_dout,
        embeddings_per_node_0_0_0_0_0110_empty_n => embeddings_per_node_0_0_0_0_0110_empty_n,
        embeddings_per_node_0_0_0_0_0110_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0110_read,
        embeddings_per_node_0_0_0_0_0111_dout => embeddings_per_node_0_0_0_0_0111_dout,
        embeddings_per_node_0_0_0_0_0111_empty_n => embeddings_per_node_0_0_0_0_0111_empty_n,
        embeddings_per_node_0_0_0_0_0111_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0111_read,
        embeddings_per_node_0_0_0_0_0112_dout => embeddings_per_node_0_0_0_0_0112_dout,
        embeddings_per_node_0_0_0_0_0112_empty_n => embeddings_per_node_0_0_0_0_0112_empty_n,
        embeddings_per_node_0_0_0_0_0112_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0112_read,
        embeddings_per_node_0_0_0_0_0113_dout => embeddings_per_node_0_0_0_0_0113_dout,
        embeddings_per_node_0_0_0_0_0113_empty_n => embeddings_per_node_0_0_0_0_0113_empty_n,
        embeddings_per_node_0_0_0_0_0113_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0113_read,
        embeddings_per_node_0_0_0_0_0114_dout => embeddings_per_node_0_0_0_0_0114_dout,
        embeddings_per_node_0_0_0_0_0114_empty_n => embeddings_per_node_0_0_0_0_0114_empty_n,
        embeddings_per_node_0_0_0_0_0114_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0114_read,
        embeddings_per_node_0_0_0_0_0115_dout => embeddings_per_node_0_0_0_0_0115_dout,
        embeddings_per_node_0_0_0_0_0115_empty_n => embeddings_per_node_0_0_0_0_0115_empty_n,
        embeddings_per_node_0_0_0_0_0115_read => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0115_read,
        bound => bound_reg_270,
        mul_ln712 => mul_ln712_reg_265,
        message_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address0,
        message_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce0,
        message_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_we0,
        message_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_d0,
        message_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address1,
        message_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce1,
        message_q1 => message_q1,
        message6_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address0,
        message6_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce0,
        message6_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_we0,
        message6_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_d0,
        message6_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address1,
        message6_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce1,
        message6_q1 => message6_q1,
        message7_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address0,
        message7_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce0,
        message7_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_we0,
        message7_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_d0,
        message7_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address1,
        message7_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce1,
        message7_q1 => message7_q1,
        message8_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address0,
        message8_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce0,
        message8_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_we0,
        message8_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_d0,
        message8_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address1,
        message8_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce1,
        message8_q1 => message8_q1,
        message9_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address0,
        message9_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce0,
        message9_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_we0,
        message9_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_d0,
        message9_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address1,
        message9_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce1,
        message9_q1 => message9_q1,
        message10_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address0,
        message10_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce0,
        message10_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_we0,
        message10_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_d0,
        message10_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address1,
        message10_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce1,
        message10_q1 => message10_q1,
        message11_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address0,
        message11_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce0,
        message11_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_we0,
        message11_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_d0,
        message11_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address1,
        message11_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce1,
        message11_q1 => message11_q1,
        message12_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address0,
        message12_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce0,
        message12_we0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_we0,
        message12_d0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_d0,
        message12_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address1,
        message12_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce1,
        message12_q1 => message12_q1,
        edge_embedding_weights_V_0_0_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address0,
        edge_embedding_weights_V_0_0_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce0,
        edge_embedding_weights_V_0_0_q0 => edge_embedding_weights_V_0_0_q0,
        edge_embedding_weights_V_0_0_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address1,
        edge_embedding_weights_V_0_0_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce1,
        edge_embedding_weights_V_0_0_q1 => edge_embedding_weights_V_0_0_q1,
        edge_embedding_weights_V_0_0_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address2,
        edge_embedding_weights_V_0_0_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce2,
        edge_embedding_weights_V_0_0_q2 => edge_embedding_weights_V_0_0_q2,
        edge_embedding_weights_V_0_1_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address0,
        edge_embedding_weights_V_0_1_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce0,
        edge_embedding_weights_V_0_1_q0 => edge_embedding_weights_V_0_1_q0,
        edge_embedding_weights_V_0_1_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address1,
        edge_embedding_weights_V_0_1_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce1,
        edge_embedding_weights_V_0_1_q1 => edge_embedding_weights_V_0_1_q1,
        edge_embedding_weights_V_0_1_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address2,
        edge_embedding_weights_V_0_1_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce2,
        edge_embedding_weights_V_0_1_q2 => edge_embedding_weights_V_0_1_q2,
        edge_embedding_weights_V_0_2_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address0,
        edge_embedding_weights_V_0_2_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce0,
        edge_embedding_weights_V_0_2_q0 => edge_embedding_weights_V_0_2_q0,
        edge_embedding_weights_V_0_2_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address1,
        edge_embedding_weights_V_0_2_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce1,
        edge_embedding_weights_V_0_2_q1 => edge_embedding_weights_V_0_2_q1,
        edge_embedding_weights_V_0_2_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address2,
        edge_embedding_weights_V_0_2_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce2,
        edge_embedding_weights_V_0_2_q2 => edge_embedding_weights_V_0_2_q2,
        edge_embedding_weights_V_0_3_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address0,
        edge_embedding_weights_V_0_3_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce0,
        edge_embedding_weights_V_0_3_q0 => edge_embedding_weights_V_0_3_q0,
        edge_embedding_weights_V_0_3_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address1,
        edge_embedding_weights_V_0_3_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce1,
        edge_embedding_weights_V_0_3_q1 => edge_embedding_weights_V_0_3_q1,
        edge_embedding_weights_V_0_3_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address2,
        edge_embedding_weights_V_0_3_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce2,
        edge_embedding_weights_V_0_3_q2 => edge_embedding_weights_V_0_3_q2,
        neighbor_tables_1_0_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_address0,
        neighbor_tables_1_0_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_ce0,
        neighbor_tables_1_0_q0 => neighbor_tables_1_0_q0,
        edge_attrs_1_0_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_address0,
        edge_attrs_1_0_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_ce0,
        edge_attrs_1_0_q0 => edge_attrs_1_0_q0,
        degree_tables_1_0_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_address0,
        degree_tables_1_0_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_ce0,
        degree_tables_1_0_q0 => degree_tables_1_0_q0,
        edge_embedding_weights_V_0_4_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address0,
        edge_embedding_weights_V_0_4_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce0,
        edge_embedding_weights_V_0_4_q0 => edge_embedding_weights_V_0_4_q0,
        edge_embedding_weights_V_0_4_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address1,
        edge_embedding_weights_V_0_4_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce1,
        edge_embedding_weights_V_0_4_q1 => edge_embedding_weights_V_0_4_q1,
        edge_embedding_weights_V_0_4_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address2,
        edge_embedding_weights_V_0_4_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce2,
        edge_embedding_weights_V_0_4_q2 => edge_embedding_weights_V_0_4_q2,
        edge_embedding_weights_V_0_5_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address0,
        edge_embedding_weights_V_0_5_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce0,
        edge_embedding_weights_V_0_5_q0 => edge_embedding_weights_V_0_5_q0,
        edge_embedding_weights_V_0_5_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address1,
        edge_embedding_weights_V_0_5_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce1,
        edge_embedding_weights_V_0_5_q1 => edge_embedding_weights_V_0_5_q1,
        edge_embedding_weights_V_0_5_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address2,
        edge_embedding_weights_V_0_5_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce2,
        edge_embedding_weights_V_0_5_q2 => edge_embedding_weights_V_0_5_q2,
        edge_embedding_weights_V_0_6_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address0,
        edge_embedding_weights_V_0_6_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce0,
        edge_embedding_weights_V_0_6_q0 => edge_embedding_weights_V_0_6_q0,
        edge_embedding_weights_V_0_6_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address1,
        edge_embedding_weights_V_0_6_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce1,
        edge_embedding_weights_V_0_6_q1 => edge_embedding_weights_V_0_6_q1,
        edge_embedding_weights_V_0_6_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address2,
        edge_embedding_weights_V_0_6_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce2,
        edge_embedding_weights_V_0_6_q2 => edge_embedding_weights_V_0_6_q2,
        edge_embedding_weights_V_0_7_address0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address0,
        edge_embedding_weights_V_0_7_ce0 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce0,
        edge_embedding_weights_V_0_7_q0 => edge_embedding_weights_V_0_7_q0,
        edge_embedding_weights_V_0_7_address1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address1,
        edge_embedding_weights_V_0_7_ce1 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce1,
        edge_embedding_weights_V_0_7_q1 => edge_embedding_weights_V_0_7_q1,
        edge_embedding_weights_V_0_7_address2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address2,
        edge_embedding_weights_V_0_7_ce2 => grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce2,
        edge_embedding_weights_V_0_7_q2 => edge_embedding_weights_V_0_7_q2);

    mul_32ns_5ns_36_2_1_U6272 : component GIN_compute_graphs_mul_32ns_5ns_36_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 5,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_244_p0,
        din1 => grp_fu_244_p1,
        ce => grp_fu_244_ce,
        dout => grp_fu_244_p2);

    mul_3ns_5ns_7_1_1_U6273 : component GIN_compute_graphs_mul_3ns_5ns_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 5,
        dout_WIDTH => 7)
    port map (
        din0 => mul_ln712_fu_254_p0,
        din1 => mul_ln712_fu_254_p1,
        dout => mul_ln712_fu_254_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_270 <= grp_fu_244_p2;
                mul_ln712_reg_265 <= mul_ln712_fu_254_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer_num_empty_n, ap_CS_fsm_state2, grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer_num_empty_n)
    begin
        if ((layer_num_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done)
    begin
        if ((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    degree_tables_1_0_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_address0;
    degree_tables_1_0_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_0_ce0;
    edge_attrs_1_0_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_address0;
    edge_attrs_1_0_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_0_ce0;
    edge_embedding_weights_V_0_0_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address0;
    edge_embedding_weights_V_0_0_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address1;
    edge_embedding_weights_V_0_0_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_address2;
    edge_embedding_weights_V_0_0_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce0;
    edge_embedding_weights_V_0_0_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce1;
    edge_embedding_weights_V_0_0_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_0_ce2;
    edge_embedding_weights_V_0_1_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address0;
    edge_embedding_weights_V_0_1_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address1;
    edge_embedding_weights_V_0_1_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_address2;
    edge_embedding_weights_V_0_1_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce0;
    edge_embedding_weights_V_0_1_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce1;
    edge_embedding_weights_V_0_1_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_1_ce2;
    edge_embedding_weights_V_0_2_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address0;
    edge_embedding_weights_V_0_2_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address1;
    edge_embedding_weights_V_0_2_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_address2;
    edge_embedding_weights_V_0_2_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce0;
    edge_embedding_weights_V_0_2_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce1;
    edge_embedding_weights_V_0_2_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_2_ce2;
    edge_embedding_weights_V_0_3_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address0;
    edge_embedding_weights_V_0_3_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address1;
    edge_embedding_weights_V_0_3_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_address2;
    edge_embedding_weights_V_0_3_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce0;
    edge_embedding_weights_V_0_3_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce1;
    edge_embedding_weights_V_0_3_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_3_ce2;
    edge_embedding_weights_V_0_4_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address0;
    edge_embedding_weights_V_0_4_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address1;
    edge_embedding_weights_V_0_4_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_address2;
    edge_embedding_weights_V_0_4_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce0;
    edge_embedding_weights_V_0_4_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce1;
    edge_embedding_weights_V_0_4_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_4_ce2;
    edge_embedding_weights_V_0_5_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address0;
    edge_embedding_weights_V_0_5_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address1;
    edge_embedding_weights_V_0_5_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_address2;
    edge_embedding_weights_V_0_5_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce0;
    edge_embedding_weights_V_0_5_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce1;
    edge_embedding_weights_V_0_5_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_5_ce2;
    edge_embedding_weights_V_0_6_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address0;
    edge_embedding_weights_V_0_6_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address1;
    edge_embedding_weights_V_0_6_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_address2;
    edge_embedding_weights_V_0_6_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce0;
    edge_embedding_weights_V_0_6_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce1;
    edge_embedding_weights_V_0_6_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_6_ce2;
    edge_embedding_weights_V_0_7_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address0;
    edge_embedding_weights_V_0_7_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address1;
    edge_embedding_weights_V_0_7_address2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_address2;
    edge_embedding_weights_V_0_7_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce0;
    edge_embedding_weights_V_0_7_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce1;
    edge_embedding_weights_V_0_7_ce2 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_0_7_ce2;

    embeddings_per_node_0_0_0_0_0110_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0110_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0110_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0110_read;
        else 
            embeddings_per_node_0_0_0_0_0110_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0111_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0111_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0111_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0111_read;
        else 
            embeddings_per_node_0_0_0_0_0111_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0112_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0112_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0112_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0112_read;
        else 
            embeddings_per_node_0_0_0_0_0112_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0113_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0113_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0113_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0113_read;
        else 
            embeddings_per_node_0_0_0_0_0113_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0114_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0114_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0114_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0114_read;
        else 
            embeddings_per_node_0_0_0_0_0114_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0115_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0115_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0115_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0115_read;
        else 
            embeddings_per_node_0_0_0_0_0115_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_018_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_018_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_018_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_018_read;
        else 
            embeddings_per_node_0_0_0_0_018_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_019_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_019_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_019_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_019_read;
        else 
            embeddings_per_node_0_0_0_0_019_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01_read;
        else 
            embeddings_per_node_0_0_0_0_01_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_02_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_02_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_02_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_02_read;
        else 
            embeddings_per_node_0_0_0_0_02_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_03_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_03_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_03_read;
        else 
            embeddings_per_node_0_0_0_0_03_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_04_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_04_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_04_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_04_read;
        else 
            embeddings_per_node_0_0_0_0_04_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_05_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_05_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_05_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_05_read;
        else 
            embeddings_per_node_0_0_0_0_05_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_06_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_06_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_06_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_06_read;
        else 
            embeddings_per_node_0_0_0_0_06_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_07_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_07_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_07_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_07_read;
        else 
            embeddings_per_node_0_0_0_0_07_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_0_read_assign_proc : process(grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_0_read <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_0_read;
        else 
            embeddings_per_node_0_0_0_0_0_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_244_ce_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_fu_244_ce <= ap_const_logic_1;
        else 
            grp_fu_244_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_244_p0 <= grp_fu_244_p00(32 - 1 downto 0);
    grp_fu_244_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num_of_edges_per_pe_1_0),36));
    grp_fu_244_p1 <= ap_const_lv36_D(5 - 1 downto 0);
    grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg;

    layer_num_blk_n_assign_proc : process(layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer_num_blk_n <= layer_num_empty_n;
        else 
            layer_num_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer_num_read_assign_proc : process(layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if (((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer_num_read <= ap_const_logic_1;
        else 
            layer_num_read <= ap_const_logic_0;
        end if; 
    end process;

    message10_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address0;
    message10_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_address1;
    message10_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce0;
    message10_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_ce1;
    message10_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_d0;
    message10_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message10_we0;
    message11_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address0;
    message11_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_address1;
    message11_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce0;
    message11_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_ce1;
    message11_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_d0;
    message11_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message11_we0;
    message12_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address0;
    message12_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_address1;
    message12_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce0;
    message12_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_ce1;
    message12_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_d0;
    message12_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message12_we0;
    message6_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address0;
    message6_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_address1;
    message6_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce0;
    message6_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_ce1;
    message6_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_d0;
    message6_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message6_we0;
    message7_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address0;
    message7_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_address1;
    message7_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce0;
    message7_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_ce1;
    message7_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_d0;
    message7_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message7_we0;
    message8_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address0;
    message8_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_address1;
    message8_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce0;
    message8_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_ce1;
    message8_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_d0;
    message8_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message8_we0;
    message9_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address0;
    message9_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_address1;
    message9_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce0;
    message9_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_ce1;
    message9_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_d0;
    message9_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message9_we0;
    message_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address0;
    message_address1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_address1;
    message_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce0;
    message_ce1 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_ce1;
    message_d0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_d0;
    message_we0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message_we0;
    mul_ln712_fu_254_p0 <= mul_ln712_fu_254_p00(3 - 1 downto 0);
    mul_ln712_fu_254_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(layer_num_dout),7));
    mul_ln712_fu_254_p1 <= ap_const_lv7_D(5 - 1 downto 0);
    neighbor_tables_1_0_address0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_address0;
    neighbor_tables_1_0_ce0 <= grp_message_passing_pe18_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_0_ce0;
end behav;
