-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1.1 (64-bit)
-- Version: 2021.1.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GIN_compute_graphs_message_passing_pe19 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer_num_dout : IN STD_LOGIC_VECTOR (2 downto 0);
    layer_num_empty_n : IN STD_LOGIC;
    layer_num_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_012_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_012_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_012_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01216_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01216_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01216_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01217_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01217_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01217_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01218_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01218_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01218_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01219_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01219_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01219_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01220_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01220_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01220_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01221_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01221_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01221_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01222_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01222_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01222_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_013_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_013_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_013_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01323_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01323_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01323_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01324_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01324_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01324_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01325_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01325_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01325_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01326_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01326_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01326_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01327_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01327_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01327_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01328_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01328_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01328_read : OUT STD_LOGIC;
    embeddings_per_node_0_0_0_0_01329_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    embeddings_per_node_0_0_0_0_01329_empty_n : IN STD_LOGIC;
    embeddings_per_node_0_0_0_0_01329_read : OUT STD_LOGIC;
    message4_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message4_ce0 : OUT STD_LOGIC;
    message4_we0 : OUT STD_LOGIC;
    message4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message4_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message4_ce1 : OUT STD_LOGIC;
    message4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message413_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message413_ce0 : OUT STD_LOGIC;
    message413_we0 : OUT STD_LOGIC;
    message413_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message413_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message413_ce1 : OUT STD_LOGIC;
    message413_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message414_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message414_ce0 : OUT STD_LOGIC;
    message414_we0 : OUT STD_LOGIC;
    message414_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message414_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message414_ce1 : OUT STD_LOGIC;
    message414_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message415_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message415_ce0 : OUT STD_LOGIC;
    message415_we0 : OUT STD_LOGIC;
    message415_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message415_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message415_ce1 : OUT STD_LOGIC;
    message415_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message416_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message416_ce0 : OUT STD_LOGIC;
    message416_we0 : OUT STD_LOGIC;
    message416_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message416_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message416_ce1 : OUT STD_LOGIC;
    message416_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message417_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message417_ce0 : OUT STD_LOGIC;
    message417_we0 : OUT STD_LOGIC;
    message417_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message417_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message417_ce1 : OUT STD_LOGIC;
    message417_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message418_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message418_ce0 : OUT STD_LOGIC;
    message418_we0 : OUT STD_LOGIC;
    message418_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message418_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message418_ce1 : OUT STD_LOGIC;
    message418_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    message419_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message419_ce0 : OUT STD_LOGIC;
    message419_we0 : OUT STD_LOGIC;
    message419_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    message419_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    message419_ce1 : OUT STD_LOGIC;
    message419_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    num_of_edges_per_pe_1_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    edge_embedding_weights_V_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_0_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_0_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_0_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_0_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_0_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_1_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_1_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_1_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_1_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_1_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_2_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_2_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_2_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_2_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_2_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_3_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_3_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_3_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_3_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_3_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    neighbor_tables_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    neighbor_tables_1_1_ce0 : OUT STD_LOGIC;
    neighbor_tables_1_1_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    edge_attrs_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    edge_attrs_1_1_ce0 : OUT STD_LOGIC;
    edge_attrs_1_1_q0 : IN STD_LOGIC_VECTOR (70 downto 0);
    degree_tables_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    degree_tables_1_1_ce0 : OUT STD_LOGIC;
    degree_tables_1_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    edge_embedding_weights_V_1_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_4_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_4_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_4_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_4_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_4_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_5_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_5_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_5_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_5_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_5_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_6_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_6_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_6_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_6_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_6_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_7_ce0 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_7_ce1 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    edge_embedding_weights_V_1_7_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    edge_embedding_weights_V_1_7_ce2 : OUT STD_LOGIC;
    edge_embedding_weights_V_1_7_q2 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of GIN_compute_graphs_message_passing_pe19 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv36_D : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000001101";
    constant ap_const_lv7_D : STD_LOGIC_VECTOR (6 downto 0) := "0001101";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer_num_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln712_fu_254_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln712_reg_265 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_244_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal bound_reg_270 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_012_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01216_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01217_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01218_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01219_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01220_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01221_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01222_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_013_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01323_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01324_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01325_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01326_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01327_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01328_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01329_read : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_we0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce0 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce1 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce2 : STD_LOGIC;
    signal grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_244_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_244_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln712_fu_254_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln712_fu_254_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_244_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal grp_fu_244_p00 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln712_fu_254_p00 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component GIN_compute_graphs_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_012_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_012_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_012_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01216_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01216_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01216_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01217_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01217_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01217_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01218_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01218_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01218_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01219_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01219_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01219_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01220_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01220_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01220_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01221_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01221_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01221_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01222_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01222_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01222_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_013_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_013_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_013_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01323_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01323_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01323_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01324_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01324_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01324_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01325_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01325_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01325_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01326_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01326_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01326_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01327_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01327_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01327_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01328_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01328_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01328_read : OUT STD_LOGIC;
        embeddings_per_node_0_0_0_0_01329_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        embeddings_per_node_0_0_0_0_01329_empty_n : IN STD_LOGIC;
        embeddings_per_node_0_0_0_0_01329_read : OUT STD_LOGIC;
        bound : IN STD_LOGIC_VECTOR (35 downto 0);
        mul_ln712 : IN STD_LOGIC_VECTOR (6 downto 0);
        message4_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message4_ce0 : OUT STD_LOGIC;
        message4_we0 : OUT STD_LOGIC;
        message4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message4_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message4_ce1 : OUT STD_LOGIC;
        message4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message413_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message413_ce0 : OUT STD_LOGIC;
        message413_we0 : OUT STD_LOGIC;
        message413_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message413_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message413_ce1 : OUT STD_LOGIC;
        message413_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message414_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message414_ce0 : OUT STD_LOGIC;
        message414_we0 : OUT STD_LOGIC;
        message414_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message414_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message414_ce1 : OUT STD_LOGIC;
        message414_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message415_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message415_ce0 : OUT STD_LOGIC;
        message415_we0 : OUT STD_LOGIC;
        message415_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message415_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message415_ce1 : OUT STD_LOGIC;
        message415_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message416_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message416_ce0 : OUT STD_LOGIC;
        message416_we0 : OUT STD_LOGIC;
        message416_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message416_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message416_ce1 : OUT STD_LOGIC;
        message416_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message417_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message417_ce0 : OUT STD_LOGIC;
        message417_we0 : OUT STD_LOGIC;
        message417_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message417_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message417_ce1 : OUT STD_LOGIC;
        message417_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message418_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message418_ce0 : OUT STD_LOGIC;
        message418_we0 : OUT STD_LOGIC;
        message418_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message418_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message418_ce1 : OUT STD_LOGIC;
        message418_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        message419_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message419_ce0 : OUT STD_LOGIC;
        message419_we0 : OUT STD_LOGIC;
        message419_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        message419_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        message419_ce1 : OUT STD_LOGIC;
        message419_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_0_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_0_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_0_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_0_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_0_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_1_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_1_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_1_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_1_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_1_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_2_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_2_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_2_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_2_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_2_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_3_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_3_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_3_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_3_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_3_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        neighbor_tables_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        neighbor_tables_1_1_ce0 : OUT STD_LOGIC;
        neighbor_tables_1_1_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
        edge_attrs_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        edge_attrs_1_1_ce0 : OUT STD_LOGIC;
        edge_attrs_1_1_q0 : IN STD_LOGIC_VECTOR (70 downto 0);
        degree_tables_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        degree_tables_1_1_ce0 : OUT STD_LOGIC;
        degree_tables_1_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        edge_embedding_weights_V_1_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_4_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_4_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_4_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_4_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_4_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_5_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_5_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_5_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_5_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_5_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_6_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_6_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_6_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_6_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_6_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_7_ce0 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_7_ce1 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        edge_embedding_weights_V_1_7_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        edge_embedding_weights_V_1_7_ce2 : OUT STD_LOGIC;
        edge_embedding_weights_V_1_7_q2 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component GIN_compute_graphs_mul_32ns_5ns_36_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component GIN_compute_graphs_mul_3ns_5ns_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160 : component GIN_compute_graphs_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start,
        ap_done => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done,
        ap_idle => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_idle,
        ap_ready => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready,
        embeddings_per_node_0_0_0_0_012_dout => embeddings_per_node_0_0_0_0_012_dout,
        embeddings_per_node_0_0_0_0_012_empty_n => embeddings_per_node_0_0_0_0_012_empty_n,
        embeddings_per_node_0_0_0_0_012_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_012_read,
        embeddings_per_node_0_0_0_0_01216_dout => embeddings_per_node_0_0_0_0_01216_dout,
        embeddings_per_node_0_0_0_0_01216_empty_n => embeddings_per_node_0_0_0_0_01216_empty_n,
        embeddings_per_node_0_0_0_0_01216_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01216_read,
        embeddings_per_node_0_0_0_0_01217_dout => embeddings_per_node_0_0_0_0_01217_dout,
        embeddings_per_node_0_0_0_0_01217_empty_n => embeddings_per_node_0_0_0_0_01217_empty_n,
        embeddings_per_node_0_0_0_0_01217_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01217_read,
        embeddings_per_node_0_0_0_0_01218_dout => embeddings_per_node_0_0_0_0_01218_dout,
        embeddings_per_node_0_0_0_0_01218_empty_n => embeddings_per_node_0_0_0_0_01218_empty_n,
        embeddings_per_node_0_0_0_0_01218_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01218_read,
        embeddings_per_node_0_0_0_0_01219_dout => embeddings_per_node_0_0_0_0_01219_dout,
        embeddings_per_node_0_0_0_0_01219_empty_n => embeddings_per_node_0_0_0_0_01219_empty_n,
        embeddings_per_node_0_0_0_0_01219_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01219_read,
        embeddings_per_node_0_0_0_0_01220_dout => embeddings_per_node_0_0_0_0_01220_dout,
        embeddings_per_node_0_0_0_0_01220_empty_n => embeddings_per_node_0_0_0_0_01220_empty_n,
        embeddings_per_node_0_0_0_0_01220_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01220_read,
        embeddings_per_node_0_0_0_0_01221_dout => embeddings_per_node_0_0_0_0_01221_dout,
        embeddings_per_node_0_0_0_0_01221_empty_n => embeddings_per_node_0_0_0_0_01221_empty_n,
        embeddings_per_node_0_0_0_0_01221_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01221_read,
        embeddings_per_node_0_0_0_0_01222_dout => embeddings_per_node_0_0_0_0_01222_dout,
        embeddings_per_node_0_0_0_0_01222_empty_n => embeddings_per_node_0_0_0_0_01222_empty_n,
        embeddings_per_node_0_0_0_0_01222_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01222_read,
        embeddings_per_node_0_0_0_0_013_dout => embeddings_per_node_0_0_0_0_013_dout,
        embeddings_per_node_0_0_0_0_013_empty_n => embeddings_per_node_0_0_0_0_013_empty_n,
        embeddings_per_node_0_0_0_0_013_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_013_read,
        embeddings_per_node_0_0_0_0_01323_dout => embeddings_per_node_0_0_0_0_01323_dout,
        embeddings_per_node_0_0_0_0_01323_empty_n => embeddings_per_node_0_0_0_0_01323_empty_n,
        embeddings_per_node_0_0_0_0_01323_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01323_read,
        embeddings_per_node_0_0_0_0_01324_dout => embeddings_per_node_0_0_0_0_01324_dout,
        embeddings_per_node_0_0_0_0_01324_empty_n => embeddings_per_node_0_0_0_0_01324_empty_n,
        embeddings_per_node_0_0_0_0_01324_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01324_read,
        embeddings_per_node_0_0_0_0_01325_dout => embeddings_per_node_0_0_0_0_01325_dout,
        embeddings_per_node_0_0_0_0_01325_empty_n => embeddings_per_node_0_0_0_0_01325_empty_n,
        embeddings_per_node_0_0_0_0_01325_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01325_read,
        embeddings_per_node_0_0_0_0_01326_dout => embeddings_per_node_0_0_0_0_01326_dout,
        embeddings_per_node_0_0_0_0_01326_empty_n => embeddings_per_node_0_0_0_0_01326_empty_n,
        embeddings_per_node_0_0_0_0_01326_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01326_read,
        embeddings_per_node_0_0_0_0_01327_dout => embeddings_per_node_0_0_0_0_01327_dout,
        embeddings_per_node_0_0_0_0_01327_empty_n => embeddings_per_node_0_0_0_0_01327_empty_n,
        embeddings_per_node_0_0_0_0_01327_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01327_read,
        embeddings_per_node_0_0_0_0_01328_dout => embeddings_per_node_0_0_0_0_01328_dout,
        embeddings_per_node_0_0_0_0_01328_empty_n => embeddings_per_node_0_0_0_0_01328_empty_n,
        embeddings_per_node_0_0_0_0_01328_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01328_read,
        embeddings_per_node_0_0_0_0_01329_dout => embeddings_per_node_0_0_0_0_01329_dout,
        embeddings_per_node_0_0_0_0_01329_empty_n => embeddings_per_node_0_0_0_0_01329_empty_n,
        embeddings_per_node_0_0_0_0_01329_read => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01329_read,
        bound => bound_reg_270,
        mul_ln712 => mul_ln712_reg_265,
        message4_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address0,
        message4_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce0,
        message4_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_we0,
        message4_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_d0,
        message4_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address1,
        message4_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce1,
        message4_q1 => message4_q1,
        message413_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address0,
        message413_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce0,
        message413_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_we0,
        message413_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_d0,
        message413_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address1,
        message413_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce1,
        message413_q1 => message413_q1,
        message414_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address0,
        message414_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce0,
        message414_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_we0,
        message414_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_d0,
        message414_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address1,
        message414_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce1,
        message414_q1 => message414_q1,
        message415_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address0,
        message415_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce0,
        message415_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_we0,
        message415_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_d0,
        message415_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address1,
        message415_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce1,
        message415_q1 => message415_q1,
        message416_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address0,
        message416_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce0,
        message416_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_we0,
        message416_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_d0,
        message416_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address1,
        message416_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce1,
        message416_q1 => message416_q1,
        message417_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address0,
        message417_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce0,
        message417_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_we0,
        message417_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_d0,
        message417_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address1,
        message417_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce1,
        message417_q1 => message417_q1,
        message418_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address0,
        message418_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce0,
        message418_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_we0,
        message418_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_d0,
        message418_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address1,
        message418_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce1,
        message418_q1 => message418_q1,
        message419_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address0,
        message419_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce0,
        message419_we0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_we0,
        message419_d0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_d0,
        message419_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address1,
        message419_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce1,
        message419_q1 => message419_q1,
        edge_embedding_weights_V_1_0_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address0,
        edge_embedding_weights_V_1_0_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce0,
        edge_embedding_weights_V_1_0_q0 => edge_embedding_weights_V_1_0_q0,
        edge_embedding_weights_V_1_0_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address1,
        edge_embedding_weights_V_1_0_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce1,
        edge_embedding_weights_V_1_0_q1 => edge_embedding_weights_V_1_0_q1,
        edge_embedding_weights_V_1_0_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address2,
        edge_embedding_weights_V_1_0_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce2,
        edge_embedding_weights_V_1_0_q2 => edge_embedding_weights_V_1_0_q2,
        edge_embedding_weights_V_1_1_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address0,
        edge_embedding_weights_V_1_1_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce0,
        edge_embedding_weights_V_1_1_q0 => edge_embedding_weights_V_1_1_q0,
        edge_embedding_weights_V_1_1_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address1,
        edge_embedding_weights_V_1_1_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce1,
        edge_embedding_weights_V_1_1_q1 => edge_embedding_weights_V_1_1_q1,
        edge_embedding_weights_V_1_1_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address2,
        edge_embedding_weights_V_1_1_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce2,
        edge_embedding_weights_V_1_1_q2 => edge_embedding_weights_V_1_1_q2,
        edge_embedding_weights_V_1_2_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address0,
        edge_embedding_weights_V_1_2_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce0,
        edge_embedding_weights_V_1_2_q0 => edge_embedding_weights_V_1_2_q0,
        edge_embedding_weights_V_1_2_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address1,
        edge_embedding_weights_V_1_2_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce1,
        edge_embedding_weights_V_1_2_q1 => edge_embedding_weights_V_1_2_q1,
        edge_embedding_weights_V_1_2_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address2,
        edge_embedding_weights_V_1_2_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce2,
        edge_embedding_weights_V_1_2_q2 => edge_embedding_weights_V_1_2_q2,
        edge_embedding_weights_V_1_3_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address0,
        edge_embedding_weights_V_1_3_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce0,
        edge_embedding_weights_V_1_3_q0 => edge_embedding_weights_V_1_3_q0,
        edge_embedding_weights_V_1_3_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address1,
        edge_embedding_weights_V_1_3_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce1,
        edge_embedding_weights_V_1_3_q1 => edge_embedding_weights_V_1_3_q1,
        edge_embedding_weights_V_1_3_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address2,
        edge_embedding_weights_V_1_3_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce2,
        edge_embedding_weights_V_1_3_q2 => edge_embedding_weights_V_1_3_q2,
        neighbor_tables_1_1_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_address0,
        neighbor_tables_1_1_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_ce0,
        neighbor_tables_1_1_q0 => neighbor_tables_1_1_q0,
        edge_attrs_1_1_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_address0,
        edge_attrs_1_1_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_ce0,
        edge_attrs_1_1_q0 => edge_attrs_1_1_q0,
        degree_tables_1_1_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_address0,
        degree_tables_1_1_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_ce0,
        degree_tables_1_1_q0 => degree_tables_1_1_q0,
        edge_embedding_weights_V_1_4_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address0,
        edge_embedding_weights_V_1_4_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce0,
        edge_embedding_weights_V_1_4_q0 => edge_embedding_weights_V_1_4_q0,
        edge_embedding_weights_V_1_4_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address1,
        edge_embedding_weights_V_1_4_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce1,
        edge_embedding_weights_V_1_4_q1 => edge_embedding_weights_V_1_4_q1,
        edge_embedding_weights_V_1_4_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address2,
        edge_embedding_weights_V_1_4_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce2,
        edge_embedding_weights_V_1_4_q2 => edge_embedding_weights_V_1_4_q2,
        edge_embedding_weights_V_1_5_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address0,
        edge_embedding_weights_V_1_5_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce0,
        edge_embedding_weights_V_1_5_q0 => edge_embedding_weights_V_1_5_q0,
        edge_embedding_weights_V_1_5_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address1,
        edge_embedding_weights_V_1_5_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce1,
        edge_embedding_weights_V_1_5_q1 => edge_embedding_weights_V_1_5_q1,
        edge_embedding_weights_V_1_5_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address2,
        edge_embedding_weights_V_1_5_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce2,
        edge_embedding_weights_V_1_5_q2 => edge_embedding_weights_V_1_5_q2,
        edge_embedding_weights_V_1_6_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address0,
        edge_embedding_weights_V_1_6_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce0,
        edge_embedding_weights_V_1_6_q0 => edge_embedding_weights_V_1_6_q0,
        edge_embedding_weights_V_1_6_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address1,
        edge_embedding_weights_V_1_6_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce1,
        edge_embedding_weights_V_1_6_q1 => edge_embedding_weights_V_1_6_q1,
        edge_embedding_weights_V_1_6_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address2,
        edge_embedding_weights_V_1_6_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce2,
        edge_embedding_weights_V_1_6_q2 => edge_embedding_weights_V_1_6_q2,
        edge_embedding_weights_V_1_7_address0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address0,
        edge_embedding_weights_V_1_7_ce0 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce0,
        edge_embedding_weights_V_1_7_q0 => edge_embedding_weights_V_1_7_q0,
        edge_embedding_weights_V_1_7_address1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address1,
        edge_embedding_weights_V_1_7_ce1 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce1,
        edge_embedding_weights_V_1_7_q1 => edge_embedding_weights_V_1_7_q1,
        edge_embedding_weights_V_1_7_address2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address2,
        edge_embedding_weights_V_1_7_ce2 => grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce2,
        edge_embedding_weights_V_1_7_q2 => edge_embedding_weights_V_1_7_q2);

    mul_32ns_5ns_36_2_1_U6354 : component GIN_compute_graphs_mul_32ns_5ns_36_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 5,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_244_p0,
        din1 => grp_fu_244_p1,
        ce => grp_fu_244_ce,
        dout => grp_fu_244_p2);

    mul_3ns_5ns_7_1_1_U6355 : component GIN_compute_graphs_mul_3ns_5ns_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 5,
        dout_WIDTH => 7)
    port map (
        din0 => mul_ln712_fu_254_p0,
        din1 => mul_ln712_fu_254_p1,
        dout => mul_ln712_fu_254_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_270 <= grp_fu_244_p2;
                mul_ln712_reg_265 <= mul_ln712_fu_254_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer_num_empty_n, ap_CS_fsm_state2, grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer_num_empty_n)
    begin
        if ((layer_num_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done)
    begin
        if ((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    degree_tables_1_1_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_address0;
    degree_tables_1_1_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_degree_tables_1_1_ce0;
    edge_attrs_1_1_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_address0;
    edge_attrs_1_1_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_attrs_1_1_ce0;
    edge_embedding_weights_V_1_0_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address0;
    edge_embedding_weights_V_1_0_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address1;
    edge_embedding_weights_V_1_0_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_address2;
    edge_embedding_weights_V_1_0_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce0;
    edge_embedding_weights_V_1_0_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce1;
    edge_embedding_weights_V_1_0_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_0_ce2;
    edge_embedding_weights_V_1_1_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address0;
    edge_embedding_weights_V_1_1_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address1;
    edge_embedding_weights_V_1_1_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_address2;
    edge_embedding_weights_V_1_1_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce0;
    edge_embedding_weights_V_1_1_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce1;
    edge_embedding_weights_V_1_1_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_1_ce2;
    edge_embedding_weights_V_1_2_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address0;
    edge_embedding_weights_V_1_2_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address1;
    edge_embedding_weights_V_1_2_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_address2;
    edge_embedding_weights_V_1_2_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce0;
    edge_embedding_weights_V_1_2_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce1;
    edge_embedding_weights_V_1_2_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_2_ce2;
    edge_embedding_weights_V_1_3_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address0;
    edge_embedding_weights_V_1_3_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address1;
    edge_embedding_weights_V_1_3_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_address2;
    edge_embedding_weights_V_1_3_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce0;
    edge_embedding_weights_V_1_3_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce1;
    edge_embedding_weights_V_1_3_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_3_ce2;
    edge_embedding_weights_V_1_4_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address0;
    edge_embedding_weights_V_1_4_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address1;
    edge_embedding_weights_V_1_4_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_address2;
    edge_embedding_weights_V_1_4_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce0;
    edge_embedding_weights_V_1_4_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce1;
    edge_embedding_weights_V_1_4_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_4_ce2;
    edge_embedding_weights_V_1_5_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address0;
    edge_embedding_weights_V_1_5_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address1;
    edge_embedding_weights_V_1_5_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_address2;
    edge_embedding_weights_V_1_5_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce0;
    edge_embedding_weights_V_1_5_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce1;
    edge_embedding_weights_V_1_5_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_5_ce2;
    edge_embedding_weights_V_1_6_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address0;
    edge_embedding_weights_V_1_6_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address1;
    edge_embedding_weights_V_1_6_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_address2;
    edge_embedding_weights_V_1_6_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce0;
    edge_embedding_weights_V_1_6_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce1;
    edge_embedding_weights_V_1_6_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_6_ce2;
    edge_embedding_weights_V_1_7_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address0;
    edge_embedding_weights_V_1_7_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address1;
    edge_embedding_weights_V_1_7_address2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_address2;
    edge_embedding_weights_V_1_7_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce0;
    edge_embedding_weights_V_1_7_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce1;
    edge_embedding_weights_V_1_7_ce2 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_edge_embedding_weights_V_1_7_ce2;

    embeddings_per_node_0_0_0_0_01216_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01216_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01216_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01216_read;
        else 
            embeddings_per_node_0_0_0_0_01216_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01217_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01217_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01217_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01217_read;
        else 
            embeddings_per_node_0_0_0_0_01217_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01218_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01218_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01218_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01218_read;
        else 
            embeddings_per_node_0_0_0_0_01218_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01219_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01219_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01219_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01219_read;
        else 
            embeddings_per_node_0_0_0_0_01219_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01220_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01220_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01220_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01220_read;
        else 
            embeddings_per_node_0_0_0_0_01220_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01221_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01221_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01221_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01221_read;
        else 
            embeddings_per_node_0_0_0_0_01221_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01222_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01222_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01222_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01222_read;
        else 
            embeddings_per_node_0_0_0_0_01222_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_012_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_012_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_012_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_012_read;
        else 
            embeddings_per_node_0_0_0_0_012_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01323_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01323_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01323_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01323_read;
        else 
            embeddings_per_node_0_0_0_0_01323_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01324_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01324_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01324_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01324_read;
        else 
            embeddings_per_node_0_0_0_0_01324_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01325_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01325_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01325_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01325_read;
        else 
            embeddings_per_node_0_0_0_0_01325_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01326_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01326_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01326_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01326_read;
        else 
            embeddings_per_node_0_0_0_0_01326_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01327_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01327_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01327_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01327_read;
        else 
            embeddings_per_node_0_0_0_0_01327_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01328_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01328_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01328_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01328_read;
        else 
            embeddings_per_node_0_0_0_0_01328_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_01329_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01329_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_01329_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_01329_read;
        else 
            embeddings_per_node_0_0_0_0_01329_read <= ap_const_logic_0;
        end if; 
    end process;


    embeddings_per_node_0_0_0_0_013_read_assign_proc : process(grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_013_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            embeddings_per_node_0_0_0_0_013_read <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_embeddings_per_node_0_0_0_0_013_read;
        else 
            embeddings_per_node_0_0_0_0_013_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_244_ce_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_fu_244_ce <= ap_const_logic_1;
        else 
            grp_fu_244_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_244_p0 <= grp_fu_244_p00(32 - 1 downto 0);
    grp_fu_244_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num_of_edges_per_pe_1_1),36));
    grp_fu_244_p1 <= ap_const_lv36_D(5 - 1 downto 0);
    grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_ap_start_reg;

    layer_num_blk_n_assign_proc : process(layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer_num_blk_n <= layer_num_empty_n;
        else 
            layer_num_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer_num_read_assign_proc : process(layer_num_empty_n, ap_CS_fsm_state2)
    begin
        if (((layer_num_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer_num_read <= ap_const_logic_1;
        else 
            layer_num_read <= ap_const_logic_0;
        end if; 
    end process;

    message413_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address0;
    message413_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_address1;
    message413_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce0;
    message413_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_ce1;
    message413_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_d0;
    message413_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message413_we0;
    message414_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address0;
    message414_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_address1;
    message414_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce0;
    message414_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_ce1;
    message414_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_d0;
    message414_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message414_we0;
    message415_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address0;
    message415_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_address1;
    message415_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce0;
    message415_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_ce1;
    message415_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_d0;
    message415_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message415_we0;
    message416_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address0;
    message416_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_address1;
    message416_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce0;
    message416_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_ce1;
    message416_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_d0;
    message416_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message416_we0;
    message417_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address0;
    message417_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_address1;
    message417_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce0;
    message417_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_ce1;
    message417_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_d0;
    message417_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message417_we0;
    message418_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address0;
    message418_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_address1;
    message418_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce0;
    message418_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_ce1;
    message418_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_d0;
    message418_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message418_we0;
    message419_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address0;
    message419_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_address1;
    message419_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce0;
    message419_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_ce1;
    message419_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_d0;
    message419_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message419_we0;
    message4_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address0;
    message4_address1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_address1;
    message4_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce0;
    message4_ce1 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_ce1;
    message4_d0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_d0;
    message4_we0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_message4_we0;
    mul_ln712_fu_254_p0 <= mul_ln712_fu_254_p00(3 - 1 downto 0);
    mul_ln712_fu_254_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(layer_num_dout),7));
    mul_ln712_fu_254_p1 <= ap_const_lv7_D(5 - 1 downto 0);
    neighbor_tables_1_1_address0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_address0;
    neighbor_tables_1_1_ce0 <= grp_message_passing_pe19_Pipeline_VITIS_LOOP_43_1_VITIS_LOOP_50_2_fu_160_neighbor_tables_1_1_ce0;
end behav;
